checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.9.12
        postgresql: false
        redis: false
    dependencies:
        before:
            - pip install tox coverage
    tests:
        override:
            -
                command: 'tox'
                idle_timeout: 300
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
    nodes:
        analysis:
            tests:
                override:
                    - py-scrutinizer-run
        tests: true
