checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['kytos/*', 'tests/*']
    excluded_paths:
        - 'kytos/web-ui/*'
build:
    environment:
        python: 3.6.3
        postgresql: false
        redis: false
    dependencies:
        before:
            - pip install coverage
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
            - py-scrutinizer-run
