checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['kytos/*', 'tests/*']
    excluded_paths:
        - 'kytos/web-ui/*'
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
    nodes:
        analysis:
            tests:
                override:
                    - py-scrutinizer-run
