checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['kytos/*', 'tests/*']
    excluded_paths:
        - 'kytos/web-ui/*'
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    dependencies:
        override:
            - true
    tests:
        before:
            - pip install coverage
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
